### PR TITLE
Implemented new Query Options in RequestBase

### PR DESCRIPTION
**Pull request by andrebrait**
It's now on par with https://graph.microsoft.io/en-us/docs/overview/query_parameters

This way, it's only necessary to implement the corresponding methods in other classes and it fixes quite a few problems, most notably a case where drive item collections would fail to be fetched, throwing an exception because it would try to set query options for `filter`, which is an unknown parameter in RequestBase's `_set_query_options`. 

See [this](https://github.com/microsoftgraph/msgraph-sdk-python/blob/a4be466f36d8f3f8c0c1d3c92fc3a54885cc6817/src/python3/request/drive_item_collection.py#L88) and [this](https://github.com/microsoftgraph/msgraph-sdk-python/blob/a4be466f36d8f3f8c0c1d3c92fc3a54885cc6817/src/msgraph/request_base.py#L165-L187), which is what caused me a few headaches.

### CODE REVIEW

**Comment by andrebrait** [comment]
I hope you guys review this soon. It's been a while since I submitted this pull request and it's an important one. The SDK doesn't even work without those modifications. If there's anything I must do before merging, please contact me.

**Comment by dpim** [comment]
Andre, thanks for the contribution and we apologize for the delay. We will consider this in our next planning cycle.

**Comment by andrebrait** [comment]
Thank you @dpim 
If there's anything I need to do or that I can help with, just tell me and I'll do it in a matter of hours, tops.

**Comment by dmahugh** [comment]
Thanks for your contribution, Andre, and for your patience. We really appreciate your help!

**Pull request merged**
