### PR TITLE
Added auth provider and session default from onedrivesdk, fixed bug `…

### PR DESCRIPTION
**Pull request by gojohnkevin**
…GraphObjectBase is not defined` on drive_item

### CODE REVIEW

**Comment by dpim** [comment]
We appreciate the contribution. We will consider this in our next planning cycle. Thanks!

**Comment by punkrokk** [comment]
is there any reason this isn't merged? Seems to solve a usability gap.

**Comment by dpim** [comment]
We hear you. There are concerns since some of these commits touch generated files and will be overwritten.

**Comment by punkrokk** [comment]
So - I think thIs is one of those things where someone spent the time to improve - there absolutely a demand here, and maybe you guys could share you concerns so the author could resolve it. Not your fault, but auth is complex for azure/o365. The easier it can be made the more adoption you will drive. I'm surprised there isn't a fully baked python sdk already. I almost didn't find this.

**Comment by caitlinrussell** [comment]
Closing as we are archiving this project

**Pull request closed without merging**
